  version: "3.7"
  services:
    aspnet-core-secrets:
      image: aspnet-core-secrets:latest
      ports:
        - "5015:5015"
      volumes:
        - type: bind
          source: ../kubernetes/appsettings.secrets.json
          target: /app/secrets/appsettings.secrets.json
        - type: bind
          source: ../kubernetes/appsettings.common.json
          target: /app/appsettings.common.json