apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aspnet-core-secrets-demo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: aspnet-core-secrets-demo
    spec:
      containers:
      - name: aspnet-core-secrets-demo
        image: imagerepo/aspnet-core-secrets:latest
        ports:
        - containerPort: 5015
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Kubernetes"
        volumeMounts:
        - name: secrets
          mountPath: /app/secrets
          readOnly: true
        - name: config-volume
          mountPath: /app
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: secret-appsettings
      - name: config-volume
        configMap:
          name: config-appsettings