apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aspnet-core-secrets-demo-deploy
  namespace: example
  labels:
    app: aspnet-core-secrets-demo
spec:
  selector:
    matchLabels:
      app: aspnet-core-secrets-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: aspnet-core-secrets-demo
    spec:
      containers:
      - name: aspnet-core-secrets-demo
        image: fakerepo/aspnet-core-secrets:1.0.1
        ports:
        - containerPort: 5015
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "kubernetes"
        volumeMounts:
        - name: secrets
          mountPath: /app/secrets
          readOnly: true
        - name: config-volume
          mountPath: /app
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: secret-appsettings
      - configMap:
          name: config-appsettings
        name: config-volume