apiVersion: v1
kind: Service
metadata:
  name: aspnet-core-secrets-demo-service
  namespace: example
spec:
  selector:
    app: aspnet-core-secrets-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5015
  type: LoadBalancer
